-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 16:06:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RoyalAcademyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RoyalAcademyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RoyalAcademyDB` DEFAULT CHARACTER SET utf8 ;
USE `RoyalAcademyDB` ;

-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`sede` (
  `idSede` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSede`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`carrera` (
  `idCarrera` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `idSede` INT(11) NOT NULL,
  PRIMARY KEY (`idCarrera`),
  INDEX `fk_Carrera_Sede1_idx` (`idSede` ASC) VISIBLE,
  CONSTRAINT `fk_Carrera_Sede1`
    FOREIGN KEY (`idSede`)
    REFERENCES `RoyalAcademyDB`.`sede` (`idSede`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`examen` (
  `idExamen` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `idCarrera` INT(11) NOT NULL,
  `tema` VARCHAR(45) NULL DEFAULT NULL,
  `materia` VARCHAR(45) NULL DEFAULT NULL,
  `disponible` BIT(1) NULL DEFAULT NULL,
  `notaAprobacion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idExamen`),
  INDEX `fk_ExamenModelo_Carrera1_idx` (`idCarrera` ASC) VISIBLE,
  CONSTRAINT `fk_ExamenModelo_Carrera1`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `RoyalAcademyDB`.`carrera` (`idCarrera`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`pregunta` (
  `idPregunta` INT(11) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idPregunta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`imagen` (
  `idImagen` INT(11) NOT NULL,
  `idPregunta` INT(11) NULL DEFAULT NULL,
  `Imagencol` BLOB NOT NULL,
  PRIMARY KEY (`idImagen`),
  INDEX `fk_Imagen_Pregunta1_idx` (`idPregunta` ASC) VISIBLE,
  CONSTRAINT `fk_Imagen_Pregunta1`
    FOREIGN KEY (`idPregunta`)
    REFERENCES `RoyalAcademyDB`.`pregunta` (`idPregunta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`usuario` (
  `idUsuario` INT(11) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `tipoUsuario` ENUM('profesor', 'alumno', 'ag', 'ap', 'as') NULL DEFAULT NULL,
  `idCarrera` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Carrera1_idx` (`idCarrera` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Carrera1`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `RoyalAcademyDB`.`carrera` (`idCarrera`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`inscripcion` (
  `Usuario_idUsuario` INT(11) NOT NULL,
  `ExamenModelo_idExamen` INT(11) NOT NULL,
  `examenRealizado` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `ExamenModelo_idExamen`),
  INDEX `fk_Usuario_has_ExamenModelo_ExamenModelo1_idx` (`ExamenModelo_idExamen` ASC) VISIBLE,
  INDEX `fk_Usuario_has_ExamenModelo_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_ExamenModelo_ExamenModelo1`
    FOREIGN KEY (`ExamenModelo_idExamen`)
    REFERENCES `RoyalAcademyDB`.`examen` (`idExamen`),
  CONSTRAINT `fk_Usuario_has_ExamenModelo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `RoyalAcademyDB`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`planillanotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`planillanotas` (
  `idUsuario` INT(11) NOT NULL,
  `idExamen` INT(11) NOT NULL,
  `notaExamen` INT(11) NULL DEFAULT NULL,
  `notaPractico` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`, `idExamen`),
  INDEX `fk_Usuario_has_ExamenModelo_ExamenModelo2_idx` (`idExamen` ASC) VISIBLE,
  INDEX `fk_Usuario_has_ExamenModelo_Usuario2_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_ExamenModelo_ExamenModelo2`
    FOREIGN KEY (`idExamen`)
    REFERENCES `RoyalAcademyDB`.`examen` (`idExamen`),
  CONSTRAINT `fk_Usuario_has_ExamenModelo_Usuario2`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `RoyalAcademyDB`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`preguntasporexamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`preguntasporexamen` (
  `idPregunta` INT(11) NOT NULL,
  `idExamen` INT(11) NOT NULL,
  PRIMARY KEY (`idPregunta`, `idExamen`),
  INDEX `fk_Pregunta_has_ExamenModelo_ExamenModelo1_idx` (`idExamen` ASC) VISIBLE,
  INDEX `fk_Pregunta_has_ExamenModelo_Pregunta1_idx` (`idPregunta` ASC) VISIBLE,
  CONSTRAINT `fk_Pregunta_has_ExamenModelo_ExamenModelo1`
    FOREIGN KEY (`idExamen`)
    REFERENCES `RoyalAcademyDB`.`examen` (`idExamen`),
  CONSTRAINT `fk_Pregunta_has_ExamenModelo_Pregunta1`
    FOREIGN KEY (`idPregunta`)
    REFERENCES `RoyalAcademyDB`.`pregunta` (`idPregunta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`respuestamodelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`respuestamodelo` (
  `idRespuesta` INT(11) NOT NULL,
  `idPregunta` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `esCorrecta` BIT(1) NOT NULL,
  PRIMARY KEY (`idRespuesta`),
  INDEX `fk_Respuesta_Pregunta_idx` (`idPregunta` ASC) VISIBLE,
  CONSTRAINT `fk_Respuesta_Pregunta`
    FOREIGN KEY (`idPregunta`)
    REFERENCES `RoyalAcademyDB`.`pregunta` (`idPregunta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RoyalAcademyDB`.`respuestaalumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoyalAcademyDB`.`respuestaalumno` (
  `idUsuario` INT(11) NOT NULL,
  `idRespuesta` INT(11) NOT NULL,
  `idExamen` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuario`, `idRespuesta`),
  INDEX `fk_usuario_has_respuestamodelo_respuestamodelo1_idx` (`idRespuesta` ASC) VISIBLE,
  INDEX `fk_usuario_has_respuestamodelo_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_respuestaalumno_examen1_idx` (`idExamen` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_respuestamodelo_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `RoyalAcademyDB`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_respuestamodelo_respuestamodelo1`
    FOREIGN KEY (`idRespuesta`)
    REFERENCES `RoyalAcademyDB`.`respuestamodelo` (`idRespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestaalumno_examen1`
    FOREIGN KEY (`idExamen`)
    REFERENCES `RoyalAcademyDB`.`examen` (`idExamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
